server.port=8080
server.tomcat.max-swallow-size=-1

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# ONNX Model Remote Storage (Hugging Face)
model.cache.dir=./models
model.v2.url=https://huggingface.co/ankitpanda336/eyewitness-forensic-models/resolve/main/eyewitness_v2.onnx?download=true
model.v2.filename=eyewitness_v2.onnx

factcheck.api.key=AIzaSyC5RmHaT6jsWRY2cQAl-IC31HhuIcYGKr0

serper.api.key=bd1f3a89693935940dd03561bae61834ff6fc040
